pipeline:
  identifier: Build_myPythonDockerRepo_1694777725562
  name: Build myPythonDockerRepo
  orgIdentifier: default
  projectIdentifier: dummy
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1694777683429
        repoName: aravindsuram/myPythonDockerRepo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1694777683429
                    repoName: aravindsuram/myPythonDockerRepo
                    build:
                      type: branch
                      spec:
                        branch: master
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
